name: Train Model

on:
  push:
    branches:
      - master  # Run when changes are pushed to the main branch

jobs:
  train:
    runs-on: ubuntu-latest  # Choose the OS for your runner (Ubuntu in this case)

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # This step checks out the code from the repository

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8  # Define the Python version you want

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install project dependencies

      - name: Run model training
        run: python scripts/train_model.py  # This will run your model training script
